/**
 * Auto-generated by scripts/generate_audio.js — DO NOT edit manually.
 * Run `npm run generate-audio` to regenerate.
 */
export const audioMap = {
  "Welcome to Measurement: Length in Centimetres and Metres!": "/assets/audio/audio_welcome_to_measurement_length_in_centimetres_and_metres_0.mp3",
  "Today we'll learn how to measure, compare, and work with lengths.": "/assets/audio/audio_today_we_ll_learn_how_to_measure_compare_and_work_with__1.mp3",
  "Are you ready to become a Measuring Champion? Let's start!": "/assets/audio/audio_are_you_ready_to_become_a_measuring_champion_let_s_star_2.mp3",
  "Emma found a ruler on her desk. What is this for? she asked Roo.": "/assets/audio/audio_emma_found_a_ruler_on_her_desk_what_is_this_for_she_ask_3.mp3",
  "This ruler helps us measure length! Each small mark is 1 centimetre.": "/assets/audio/audio_this_ruler_helps_us_measure_length_each_small_mark_is_1_4.mp3",
  "Each mark on a ruler equals 1 centimetre!": "/assets/audio/audio_each_mark_on_a_ruler_equals_1_centimetre__5.mp3",
  "A ruler is our measuring superpower!": "/assets/audio/audio_a_ruler_is_our_measuring_superpower__6.mp3",
  "Oliver placed his pencil on the ruler. It reaches all the way to 15!": "/assets/audio/audio_oliver_placed_his_pencil_on_the_ruler_it_reaches_all_th_7.mp3",
  "That means your pencil is 15 centimetres long — or 15 cm! said Roo.": "/assets/audio/audio_that_means_your_pencil_is_15_centimetres_long_or_15_cm__8.mp3",
  "Always start from zero! Read the number at the end — that is the length!": "/assets/audio/audio_always_start_from_zero_read_the_number_at_the_end_that__9.mp3",
  "Roo, how long is the classroom door? asked Emma.": "/assets/audio/audio_roo_how_long_is_the_classroom_door_asked_emma__10.mp3",
  "It is too long for centimetres! We use metres for long things.": "/assets/audio/audio_it_is_too_long_for_centimetres_we_use_metres_for_long_t_11.mp3",
  "100 centimetres make 1 metre — and we write it as 1 m!": "/assets/audio/audio_100_centimetres_make_1_metre_and_we_write_it_as_1_m__12.mp3",
  "Big things need big units!": "/assets/audio/audio_big_things_need_big_units__13.mp3",
  "Now we can measure anything with centimetres and metres!": "/assets/audio/audio_now_we_can_measure_anything_with_centimetres_and_metres_14.mp3",
  "You are now Measuring Champions! Let us practise!": "/assets/audio/audio_you_are_now_measuring_champions_let_us_practise__15.mp3",
  "This object starts at zero. Where does it end? Tap the number on the ruler!": "/assets/audio/audio_this_object_starts_at_zero_where_does_it_end_tap_the_nu_16.mp3",
  "Which is the shortest? Tap the bars from shortest to longest!": "/assets/audio/audio_which_is_the_shortest_tap_the_bars_from_shortest_to_lon_17.mp3",
  "Fill in the blank! Use the number pad.": "/assets/audio/audio_fill_in_the_blank_use_the_number_pad__18.mp3",
  "You ordered them from shortest to longest! Well done!": "/assets/audio/audio_you_ordered_them_from_shortest_to_longest_well_done__19.mp3",
  "Correct! You completed the length sentence!": "/assets/audio/audio_correct_you_completed_the_length_sentence__20.mp3",
  "Correct! Great work!": "/assets/audio/audio_correct_great_work__21.mp3",
  "Not quite — let's look at the explanation.": "/assets/audio/audio_not_quite_let_s_look_at_the_explanation__22.mp3",
  "What did you learn about measurement today?": "/assets/audio/audio_what_did_you_learn_about_measurement_today__23.mp3",
  "How confident do you feel about measuring with centimetres and metres?": "/assets/audio/audio_how_confident_do_you_feel_about_measuring_with_centimet_24.mp3",
  "Amazing work! You are a Measuring Champion!": "/assets/audio/audio_amazing_work_you_are_a_measuring_champion__25.mp3",
  "You have learned to measure with centimetres and metres.": "/assets/audio/audio_you_have_learned_to_measure_with_centimetres_and_metres_26.mp3",
};
