/**
 * audioMap.js
 * Auto-generated by scripts/generate_audio.js
 * DO NOT EDIT MANUALLY — run `node scripts/generate_audio.js` to regenerate.
 *
 * Key   → exact text spoken (must match 1:1 with narration.js and UI text)
 * Value → path to pre-generated .mp3 file in public/assets/audio/
 */

export const audioMap = {
  // ─── WONDER PHASE ────────────────────────────────────────────────────────
  "Welcome to the Great World Market! Alex and Emma have discovered a secret recipe map — but it's written entirely in ratios. Three parts pepper for every two parts salt. Can you help them decode it?":
    "/assets/audio/wonder_w1_hook.mp3",
  "If we want six bags of salt, how many bags of pepper do we need?":
    "/assets/audio/wonder_w1_question.mp3",
  "Excellent! Six bags of salt is three times the two-part ratio, so we need three times the three parts of pepper — that's nine bags! You already understand ratios!":
    "/assets/audio/wonder_w1_correct.mp3",
  "Good try! Remember — ratios scale by multiplication. Six divided by two gives us the scale factor of three. Three times three pepper parts gives nine bags!":
    "/assets/audio/wonder_w1_wrong.mp3",
  "At the Speed Speedway, Zara faces a challenger! The rival boasts: I do one hundred twenty metres in six seconds! Zara replies: I do ninety metres in three seconds. But who is actually faster?":
    "/assets/audio/wonder_w2_hook.mp3",
  "Calculate the unit rate — speed per second. Who is faster?":
    "/assets/audio/wonder_w2_question.mp3",
  "That's right! Zara's speed is ninety divided by three — thirty metres per second. The rival's speed is one hundred twenty divided by six — only twenty metres per second. Zara wins!":
    "/assets/audio/wonder_w2_correct.mp3",
  "Leo stands at the Gold Exchange vault! A banker offers: Deposit five hundred gold coins at ten percent simple interest per year. Leo asks: how much interest will I earn in two years?":
    "/assets/audio/wonder_w3_hook.mp3",
  "Calculate the simple interest using I equals P times R times T divided by one hundred.":
    "/assets/audio/wonder_w3_question.mp3",
  "Perfect! Ten percent of five hundred is fifty coins per year. Over two years, that's one hundred coins total interest!":
    "/assets/audio/wonder_w3_correct.mp3",

  // ─── STORY PHASE ─────────────────────────────────────────────────────────
  "Deep within the Great World Market, a legendary challenge has begun! Only those who master the language of ratios may claim the Golden Scale Trophy.":
    "/assets/audio/story_w1_01.mp3",
  "Alex unrolled the ancient scroll. It was filled with strange symbols — pairs of numbers separated by colons. This must be the ratio code!":
    "/assets/audio/story_w1_02.mp3",
  "Emma leaned over. A ratio is just a way of comparing two quantities. Three colon two means for every three of one thing, there are two of another.":
    "/assets/audio/story_w1_03.mp3",
  "But Emma — how do we know if two ratios are describing the same relationship? asked Alex, scratching his head.":
    "/assets/audio/story_w1_04.mp3",
  "Good question! If you multiply or divide both parts by the same number, you get an equivalent ratio. Three colon two is the same as six colon four, or nine colon six!":
    "/assets/audio/story_w1_05.mp3",
  "Alex's eyes lit up. So ratios can be simplified — just like fractions! We find the greatest common factor and divide!":
    "/assets/audio/story_w1_06.mp3",
  "The spice merchant smiled. You've cracked the first code! Now you may enter the Bazaar. But beware — the next challenge requires comparing rates!":
    "/assets/audio/story_w1_07.mp3",
  "The Speed Speedway roared with engines! Zara stepped up to the starting line, eyes fierce. I calculate speed before I race. Knowledge is my real engine.":
    "/assets/audio/story_w2_01.mp3",
  "A unit rate tells you how much of one thing happens per single unit of another. Like kilometres per hour — distance per one hour.":
    "/assets/audio/story_w2_02.mp3",
  "Zara challenged her rival. You say one hundred twenty kilometres in six hours. I say ninety kilometres in three hours. Shall we find our unit rates?":
    "/assets/audio/story_w2_03.mp3",
  "The rival gulped. One hundred twenty divided by six is twenty kilometres per hour. Zara smiled — ninety divided by three is thirty! I'm fifty percent faster!":
    "/assets/audio/story_w2_04.mp3",
  "Two ratios form a proportion when they're equal. Cross-multiply to check — if a times d equals b times c, the ratios are proportional!":
    "/assets/audio/story_w2_05.mp3",
  "And that is how Zara won the Speedway — not just with speed, but with mathematics!":
    "/assets/audio/story_w2_06.mp3",
  "Leo polished his golden abacus. The Gold Exchange was the most complex district of all — percentages, profit, loss, and the mysterious art of simple interest.":
    "/assets/audio/story_w3_01.mp3",
  "Percent means per hundred. So forty percent simply means forty out of every hundred. It's a special ratio where the second term is always one hundred!":
    "/assets/audio/story_w3_02.mp3",
  "Leo explained profit and loss with a smile. If you buy at a low price and sell higher — that difference over the cost price, expressed as a percentage, is your profit percent.":
    "/assets/audio/story_w3_03.mp3",
  "And simple interest? Leo tapped the formula on the wall. Interest equals Principal times Rate times Time, all divided by one hundred. Linear. Predictable. Powerful.":
    "/assets/audio/story_w3_04.mp3",
  "With this knowledge, Leo turned five hundred coins into six hundred in just two years. The merchants of the Gold Exchange bowed in respect.":
    "/assets/audio/story_w3_05.mp3",

  // ─── SIMULATE PHASE ──────────────────────────────────────────────────────
  "Welcome to the Ratio Bar Builder! Drag the sliders to adjust the quantities and watch how the ratio changes. Try to find two ratios that look the same!":
    "/assets/audio/sim_ratio_bar_intro.mp3",
  "Amazing! You discovered that three colon two and six colon four look identical when the bars are the same length. They are equivalent ratios — related by a scale factor!":
    "/assets/audio/sim_ratio_bar_discovery.mp3",
  "Now meet the Proportion Scale! Place your ratio tokens on each side and try to balance it. When both sides are equal — you've found a proportion!":
    "/assets/audio/sim_scale_intro.mp3",
  "Yes! When the scale balances, a times d always equals b times c. That's the cross-multiplication rule for proportions!":
    "/assets/audio/sim_scale_discovery.mp3",
  "Welcome to the Rate Speedway! Each car has a distance and a time. Divide to find its unit rate. Then see who wins the race!":
    "/assets/audio/sim_speedway_intro.mp3",
  "Unit rate confirmed! Distance divided by time gives you the rate per single unit. That's how we compare speeds fairly.":
    "/assets/audio/sim_speedway_discovery.mp3",
  "This is Leo's Coin Vault! Turn the dial to choose a percentage and watch exactly that many coins flow out of a hundred. Percent means per hundred!":
    "/assets/audio/sim_vault_intro.mp3",
  "That's it! You can see that forty percent of one hundred is exactly forty coins. The percentage bar makes it visual!":
    "/assets/audio/sim_vault_discovery.mp3",
  "Step into the Simple Interest Time Machine! Set the principal, rate, and time — then watch Leo's coins grow year by year. The formula I equals P times R times T over one hundred powers the machine!":
    "/assets/audio/sim_interest_intro.mp3",
  "Perfect! The coins grow linearly — the same amount each year. That's what makes it simple interest. Now verify your formula result matches the animation!":
    "/assets/audio/sim_interest_discovery.mp3",

  // ─── PLAY PHASE ──────────────────────────────────────────────────────────
  "Great work! Now let's practise what you've discovered. Choose a mode to begin!":
    "/assets/audio/play_intro.mp3",
  "Excellent answer! You've got it!": "/assets/audio/play_correct_1.mp3",
  "Brilliant reasoning! Keep going!": "/assets/audio/play_correct_2.mp3",
  "That's exactly right! Well done!": "/assets/audio/play_correct_3.mp3",
  "Not quite — but you're close! Think about the scale factor.":
    "/assets/audio/play_wrong_1.mp3",
  "Almost! Remember to divide both terms by the same number.":
    "/assets/audio/play_wrong_2.mp3",
  "The Boss Battle begins! Answer five questions correctly to defeat the Market Boss and claim your trophy!":
    "/assets/audio/boss_intro.mp3",
  "You defeated the Boss! The Golden Scale Trophy is yours!":
    "/assets/audio/boss_win.mp3",

  // ─── REFLECT PHASE ───────────────────────────────────────────────────────
  "Congratulations! You've completed this World! Let's see how well you mastered the concepts.":
    "/assets/audio/reflect_intro.mp3",
  "Your mastery scores are outstanding! You've earned a badge and a printable worksheet. Well done, champion!":
    "/assets/audio/reflect_complete.mp3",
};
