/**
 * audioMap.js — AUTO-GENERATED by scripts/generate_audio.js
 * DO NOT EDIT MANUALLY.
 * Re-run `node scripts/generate_audio.js` to regenerate.
 */

export const audioMap = {
  `Hmm, I wonder! Look at this question carefully. Two quantities are being compared in a special way. Can you spot the pattern? Think it through — then click Let's Discover!`: '/assets/audio/audio_encouragement_f7067ba59c.mp3',
  `Ooh, a speed challenge! A car travels a certain distance in a set time. When we compare distance to time, we get a rate. Can you work out how far it goes at the same speed?`: '/assets/audio/audio_encouragement_b723c96bdc.mp3',
  `Welcome to the Spice Bazaar! Alex mixes 2 bags of pepper with 3 bags of salt every morning. Today, a huge order arrives needing 6 bags of pepper. How much salt keeps the same flavour? This is exactly what ratios help us solve!`: '/assets/audio/audio_statement_42de356910.mp3',
  `A ratio compares two quantities of the same type. Alex's blend is 2 colon 3 — for every 2 bags of pepper, there are 3 bags of salt. The ratio stays exactly the same even when the amounts get bigger or smaller!`: '/assets/audio/audio_statement_1f7eaa7b15.mp3',
  `Now meet rates! Emma's car travels 120 kilometres in 2 hours. A rate compares two different units — distance and time. We write it as 60 kilometres per hour. Whenever you see the word per, you are looking at a rate!`: '/assets/audio/audio_statement_e20187ea44.mp3',
  `When two ratios are equal, they form a proportion! If 5 pens cost 3 dollars, then 10 pens cost 6 dollars — the ratio stays the same. We verify using cross-multiplication: multiply diagonally, and if both products match, it is a proportion!`: '/assets/audio/audio_statement_8f10bee959.mp3',
  `Fantastic work! You have learned three powerful ideas. Ratios compare same-type quantities like 2 colon 3. Rates compare different units like 60 kilometres per hour. And proportions are two equal ratios. You are ready to practise — let's go!`: '/assets/audio/audio_celebration_14a5535c93.mp3',
  `Station one — the Ratio Builder! Simplify each ratio to its lowest terms. Find the number that divides evenly into both parts — that is your scale factor. Let's go!`: '/assets/audio/audio_statement_6e2c779f42.mp3',
  `Station two — Rate Detective! You have a distance and a time. Divide the distance by the time to find the speed in kilometres per hour. Crack the code!`: '/assets/audio/audio_statement_883ca7a087.mp3',
  `Final station — the Proportion Checker! Two ratios are shown. Use cross-multiplication to decide if they are equal. If both diagonal products match, it is a true proportion!`: '/assets/audio/audio_statement_62ad590475.mp3',
  `Excellent answer! You've got it!`: '/assets/audio/audio_celebration_d11e66e538.mp3',
  `Brilliant reasoning! Keep going!`: '/assets/audio/audio_encouragement_6195e56eef.mp3',
  `That's exactly right! Well done!`: '/assets/audio/audio_celebration_c2c5568b3a.mp3',
  `Not quite, but good try! Read the question again and think it through.`: '/assets/audio/audio_thinking_78feedbc6d.mp3',
  `Almost there! Check your working carefully and try again.`: '/assets/audio/audio_thinking_afce2f61ad.mp3',
  `The Boss Battle begins! Answer five questions correctly to defeat the Market Boss and claim your trophy!`: '/assets/audio/audio_emphasis_f7fc615473.mp3',
  `You defeated the Boss! The Golden Scale Trophy is yours!`: '/assets/audio/audio_celebration_5741d27f15.mp3',
  `Hit! Keep going!`: '/assets/audio/audio_celebration_4084ef53cb.mp3',
  `The boss blocks! Watch out!`: '/assets/audio/audio_thinking_088dcdb314.mp3',
};
